package cn.jbg.cmab.backend.mall.bean;

import java.math.BigDecimal;

public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_id
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_belong
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    private Long itemBelong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_name
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_price
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    private BigDecimal itemPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_img
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    private String itemImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_sales
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    private Integer itemSales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_inventory
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    private Integer itemInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_desc
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    private String itemDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_rate
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    private Integer itemRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_credit
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    private Integer itemCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.checkout_tag
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    private Integer checkoutTag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_id
     *
     * @return the value of item.item_id
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_id
     *
     * @param itemId the value for item.item_id
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_belong
     *
     * @return the value of item.item_belong
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public Long getItemBelong() {
        return itemBelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_belong
     *
     * @param itemBelong the value for item.item_belong
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public void setItemBelong(Long itemBelong) {
        this.itemBelong = itemBelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_name
     *
     * @return the value of item.item_name
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_name
     *
     * @param itemName the value for item.item_name
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_price
     *
     * @return the value of item.item_price
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public BigDecimal getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_price
     *
     * @param itemPrice the value for item.item_price
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public void setItemPrice(BigDecimal itemPrice) {
        this.itemPrice = itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_img
     *
     * @return the value of item.item_img
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public String getItemImg() {
        return itemImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_img
     *
     * @param itemImg the value for item.item_img
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public void setItemImg(String itemImg) {
        this.itemImg = itemImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_sales
     *
     * @return the value of item.item_sales
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public Integer getItemSales() {
        return itemSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_sales
     *
     * @param itemSales the value for item.item_sales
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public void setItemSales(Integer itemSales) {
        this.itemSales = itemSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_inventory
     *
     * @return the value of item.item_inventory
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public Integer getItemInventory() {
        return itemInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_inventory
     *
     * @param itemInventory the value for item.item_inventory
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public void setItemInventory(Integer itemInventory) {
        this.itemInventory = itemInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_desc
     *
     * @return the value of item.item_desc
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_desc
     *
     * @param itemDesc the value for item.item_desc
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_rate
     *
     * @return the value of item.item_rate
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public Integer getItemRate() {
        return itemRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_rate
     *
     * @param itemRate the value for item.item_rate
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public void setItemRate(Integer itemRate) {
        this.itemRate = itemRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_credit
     *
     * @return the value of item.item_credit
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public Integer getItemCredit() {
        return itemCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_credit
     *
     * @param itemCredit the value for item.item_credit
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public void setItemCredit(Integer itemCredit) {
        this.itemCredit = itemCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.checkout_tag
     *
     * @return the value of item.checkout_tag
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public Integer getCheckoutTag() {
        return checkoutTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.checkout_tag
     *
     * @param checkoutTag the value for item.checkout_tag
     *
     * @mbggenerated Sat Apr 28 15:11:08 CST 2018
     */
    public void setCheckoutTag(Integer checkoutTag) {
        this.checkoutTag = checkoutTag;
    }
}