package cn.jbg.cmab.backend.mall.bean;

import java.util.Date;

public class Review {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.review_id
     *
     * @mbggenerated Sun Apr 22 20:26:40 CST 2018
     */
    private Long reviewId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.item_id
     *
     * @mbggenerated Sun Apr 22 20:26:40 CST 2018
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.user_id
     *
     * @mbggenerated Sun Apr 22 20:26:40 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.review_time
     *
     * @mbggenerated Sun Apr 22 20:26:40 CST 2018
     */
    private Date reviewTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.review_content
     *
     * @mbggenerated Sun Apr 22 20:26:40 CST 2018
     */
    private String reviewContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.review_id
     *
     * @return the value of review.review_id
     *
     * @mbggenerated Sun Apr 22 20:26:40 CST 2018
     */
    public Long getReviewId() {
        return reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.review_id
     *
     * @param reviewId the value for review.review_id
     *
     * @mbggenerated Sun Apr 22 20:26:40 CST 2018
     */
    public void setReviewId(Long reviewId) {
        this.reviewId = reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.item_id
     *
     * @return the value of review.item_id
     *
     * @mbggenerated Sun Apr 22 20:26:40 CST 2018
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.item_id
     *
     * @param itemId the value for review.item_id
     *
     * @mbggenerated Sun Apr 22 20:26:40 CST 2018
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.user_id
     *
     * @return the value of review.user_id
     *
     * @mbggenerated Sun Apr 22 20:26:40 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.user_id
     *
     * @param userId the value for review.user_id
     *
     * @mbggenerated Sun Apr 22 20:26:40 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.review_time
     *
     * @return the value of review.review_time
     *
     * @mbggenerated Sun Apr 22 20:26:40 CST 2018
     */
    public Date getReviewTime() {
        return reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.review_time
     *
     * @param reviewTime the value for review.review_time
     *
     * @mbggenerated Sun Apr 22 20:26:40 CST 2018
     */
    public void setReviewTime(Date reviewTime) {
        this.reviewTime = reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.review_content
     *
     * @return the value of review.review_content
     *
     * @mbggenerated Sun Apr 22 20:26:40 CST 2018
     */
    public String getReviewContent() {
        return reviewContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.review_content
     *
     * @param reviewContent the value for review.review_content
     *
     * @mbggenerated Sun Apr 22 20:26:40 CST 2018
     */
    public void setReviewContent(String reviewContent) {
        this.reviewContent = reviewContent;
    }
}