package cn.jbg.cmab.backend.mall.bean;

import java.util.Date;

public class UsedGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column used_goods.goods_id
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column used_goods.goods_name
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column used_goods.goods_price
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    private String goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column used_goods.goods_img
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    private String goodsImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column used_goods.goods_num
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    private Integer goodsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column used_goods.goods_desc
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    private String goodsDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column used_goods.user_id
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column used_goods.onsale_time
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    private Date onsaleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column used_goods.goods_tag
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    private Integer goodsTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column used_goods.buyer_id
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    private Long buyerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column used_goods.checkout_tag
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    private Integer checkoutTag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column used_goods.goods_id
     *
     * @return the value of used_goods.goods_id
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column used_goods.goods_id
     *
     * @param goodsId the value for used_goods.goods_id
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column used_goods.goods_name
     *
     * @return the value of used_goods.goods_name
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column used_goods.goods_name
     *
     * @param goodsName the value for used_goods.goods_name
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column used_goods.goods_price
     *
     * @return the value of used_goods.goods_price
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public String getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column used_goods.goods_price
     *
     * @param goodsPrice the value for used_goods.goods_price
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public void setGoodsPrice(String goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column used_goods.goods_img
     *
     * @return the value of used_goods.goods_img
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column used_goods.goods_img
     *
     * @param goodsImg the value for used_goods.goods_img
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column used_goods.goods_num
     *
     * @return the value of used_goods.goods_num
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public Integer getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column used_goods.goods_num
     *
     * @param goodsNum the value for used_goods.goods_num
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public void setGoodsNum(Integer goodsNum) {
        this.goodsNum = goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column used_goods.goods_desc
     *
     * @return the value of used_goods.goods_desc
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public String getGoodsDesc() {
        return goodsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column used_goods.goods_desc
     *
     * @param goodsDesc the value for used_goods.goods_desc
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public void setGoodsDesc(String goodsDesc) {
        this.goodsDesc = goodsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column used_goods.user_id
     *
     * @return the value of used_goods.user_id
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column used_goods.user_id
     *
     * @param userId the value for used_goods.user_id
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column used_goods.onsale_time
     *
     * @return the value of used_goods.onsale_time
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public Date getOnsaleTime() {
        return onsaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column used_goods.onsale_time
     *
     * @param onsaleTime the value for used_goods.onsale_time
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public void setOnsaleTime(Date onsaleTime) {
        this.onsaleTime = onsaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column used_goods.goods_tag
     *
     * @return the value of used_goods.goods_tag
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public Integer getGoodsTag() {
        return goodsTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column used_goods.goods_tag
     *
     * @param goodsTag the value for used_goods.goods_tag
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public void setGoodsTag(Integer goodsTag) {
        this.goodsTag = goodsTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column used_goods.buyer_id
     *
     * @return the value of used_goods.buyer_id
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public Long getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column used_goods.buyer_id
     *
     * @param buyerId the value for used_goods.buyer_id
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public void setBuyerId(Long buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column used_goods.checkout_tag
     *
     * @return the value of used_goods.checkout_tag
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public Integer getCheckoutTag() {
        return checkoutTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column used_goods.checkout_tag
     *
     * @param checkoutTag the value for used_goods.checkout_tag
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    public void setCheckoutTag(Integer checkoutTag) {
        this.checkoutTag = checkoutTag;
    }
}