package cn.jbg.cmab.backend.store.bean;

public class Store {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_id
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    private Long storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_belong
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    private Long storeBelong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.addr
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.map_addr
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    private String mapAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_name
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_img
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    private String storeImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_phone
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    private String storePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.business_hours
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    private String businessHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_manager
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    private String storeManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.service_type
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    private String serviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_rate
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    private Integer storeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.customer_num
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    private Integer customerNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_desc
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    private String storeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.checkout_tag
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    private Integer checkoutTag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_id
     *
     * @return the value of store.store_id
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_id
     *
     * @param storeId the value for store.store_id
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_belong
     *
     * @return the value of store.store_belong
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public Long getStoreBelong() {
        return storeBelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_belong
     *
     * @param storeBelong the value for store.store_belong
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public void setStoreBelong(Long storeBelong) {
        this.storeBelong = storeBelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.addr
     *
     * @return the value of store.addr
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.addr
     *
     * @param addr the value for store.addr
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.map_addr
     *
     * @return the value of store.map_addr
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public String getMapAddr() {
        return mapAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.map_addr
     *
     * @param mapAddr the value for store.map_addr
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public void setMapAddr(String mapAddr) {
        this.mapAddr = mapAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_name
     *
     * @return the value of store.store_name
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_name
     *
     * @param storeName the value for store.store_name
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_img
     *
     * @return the value of store.store_img
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public String getStoreImg() {
        return storeImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_img
     *
     * @param storeImg the value for store.store_img
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public void setStoreImg(String storeImg) {
        this.storeImg = storeImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_phone
     *
     * @return the value of store.store_phone
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public String getStorePhone() {
        return storePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_phone
     *
     * @param storePhone the value for store.store_phone
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public void setStorePhone(String storePhone) {
        this.storePhone = storePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.business_hours
     *
     * @return the value of store.business_hours
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public String getBusinessHours() {
        return businessHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.business_hours
     *
     * @param businessHours the value for store.business_hours
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public void setBusinessHours(String businessHours) {
        this.businessHours = businessHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_manager
     *
     * @return the value of store.store_manager
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public String getStoreManager() {
        return storeManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_manager
     *
     * @param storeManager the value for store.store_manager
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public void setStoreManager(String storeManager) {
        this.storeManager = storeManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.service_type
     *
     * @return the value of store.service_type
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.service_type
     *
     * @param serviceType the value for store.service_type
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_rate
     *
     * @return the value of store.store_rate
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public Integer getStoreRate() {
        return storeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_rate
     *
     * @param storeRate the value for store.store_rate
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public void setStoreRate(Integer storeRate) {
        this.storeRate = storeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.customer_num
     *
     * @return the value of store.customer_num
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public Integer getCustomerNum() {
        return customerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.customer_num
     *
     * @param customerNum the value for store.customer_num
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public void setCustomerNum(Integer customerNum) {
        this.customerNum = customerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_desc
     *
     * @return the value of store.store_desc
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public String getStoreDesc() {
        return storeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_desc
     *
     * @param storeDesc the value for store.store_desc
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public void setStoreDesc(String storeDesc) {
        this.storeDesc = storeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.checkout_tag
     *
     * @return the value of store.checkout_tag
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public Integer getCheckoutTag() {
        return checkoutTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.checkout_tag
     *
     * @param checkoutTag the value for store.checkout_tag
     *
     * @mbggenerated Mon May 14 01:24:39 CST 2018
     */
    public void setCheckoutTag(Integer checkoutTag) {
        this.checkoutTag = checkoutTag;
    }
}