package cn.jbg.cmab.backend.admin.bean;

public class Administrator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.admin_id
     *
     * @mbggenerated Sun Apr 22 20:11:57 CST 2018
     */
    private Long adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.username
     *
     * @mbggenerated Sun Apr 22 20:11:57 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.admin_password
     *
     * @mbggenerated Sun Apr 22 20:11:57 CST 2018
     */
    private String adminPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.admin_id
     *
     * @return the value of administrator.admin_id
     *
     * @mbggenerated Sun Apr 22 20:11:57 CST 2018
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.admin_id
     *
     * @param adminId the value for administrator.admin_id
     *
     * @mbggenerated Sun Apr 22 20:11:57 CST 2018
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.username
     *
     * @return the value of administrator.username
     *
     * @mbggenerated Sun Apr 22 20:11:57 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.username
     *
     * @param username the value for administrator.username
     *
     * @mbggenerated Sun Apr 22 20:11:57 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.admin_password
     *
     * @return the value of administrator.admin_password
     *
     * @mbggenerated Sun Apr 22 20:11:57 CST 2018
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.admin_password
     *
     * @param adminPassword the value for administrator.admin_password
     *
     * @mbggenerated Sun Apr 22 20:11:57 CST 2018
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }
}