package cn.jbg.cmab.backend.admin.bean;

public class Staff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_id
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    private Long staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_addr
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    private String staffAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_name
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    private String staffName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_phone
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    private String staffPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_email
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    private String staffEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.job_number
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    private String jobNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_authority
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    private String staffAuthority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_desc
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    private String staffDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_id
     *
     * @return the value of staff.staff_id
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public Long getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_id
     *
     * @param staffId the value for staff.staff_id
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public void setStaffId(Long staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_addr
     *
     * @return the value of staff.staff_addr
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public String getStaffAddr() {
        return staffAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_addr
     *
     * @param staffAddr the value for staff.staff_addr
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public void setStaffAddr(String staffAddr) {
        this.staffAddr = staffAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_name
     *
     * @return the value of staff.staff_name
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_name
     *
     * @param staffName the value for staff.staff_name
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_phone
     *
     * @return the value of staff.staff_phone
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public String getStaffPhone() {
        return staffPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_phone
     *
     * @param staffPhone the value for staff.staff_phone
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public void setStaffPhone(String staffPhone) {
        this.staffPhone = staffPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_email
     *
     * @return the value of staff.staff_email
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public String getStaffEmail() {
        return staffEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_email
     *
     * @param staffEmail the value for staff.staff_email
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public void setStaffEmail(String staffEmail) {
        this.staffEmail = staffEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.job_number
     *
     * @return the value of staff.job_number
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public String getJobNumber() {
        return jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.job_number
     *
     * @param jobNumber the value for staff.job_number
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_authority
     *
     * @return the value of staff.staff_authority
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public String getStaffAuthority() {
        return staffAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_authority
     *
     * @param staffAuthority the value for staff.staff_authority
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public void setStaffAuthority(String staffAuthority) {
        this.staffAuthority = staffAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_desc
     *
     * @return the value of staff.staff_desc
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public String getStaffDesc() {
        return staffDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_desc
     *
     * @param staffDesc the value for staff.staff_desc
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public void setStaffDesc(String staffDesc) {
        this.staffDesc = staffDesc;
    }
}