package cn.jbg.cmab.backend.admin.bean;

import java.util.ArrayList;
import java.util.List;

public class StaffExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table staff
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table staff
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table staff
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public StaffExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table staff
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStaffIdIsNull() {
            addCriterion("staff_id is null");
            return (Criteria) this;
        }

        public Criteria andStaffIdIsNotNull() {
            addCriterion("staff_id is not null");
            return (Criteria) this;
        }

        public Criteria andStaffIdEqualTo(Long value) {
            addCriterion("staff_id =", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotEqualTo(Long value) {
            addCriterion("staff_id <>", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdGreaterThan(Long value) {
            addCriterion("staff_id >", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdGreaterThanOrEqualTo(Long value) {
            addCriterion("staff_id >=", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdLessThan(Long value) {
            addCriterion("staff_id <", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdLessThanOrEqualTo(Long value) {
            addCriterion("staff_id <=", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdIn(List<Long> values) {
            addCriterion("staff_id in", values, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotIn(List<Long> values) {
            addCriterion("staff_id not in", values, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdBetween(Long value1, Long value2) {
            addCriterion("staff_id between", value1, value2, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotBetween(Long value1, Long value2) {
            addCriterion("staff_id not between", value1, value2, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffAddrIsNull() {
            addCriterion("staff_addr is null");
            return (Criteria) this;
        }

        public Criteria andStaffAddrIsNotNull() {
            addCriterion("staff_addr is not null");
            return (Criteria) this;
        }

        public Criteria andStaffAddrEqualTo(String value) {
            addCriterion("staff_addr =", value, "staffAddr");
            return (Criteria) this;
        }

        public Criteria andStaffAddrNotEqualTo(String value) {
            addCriterion("staff_addr <>", value, "staffAddr");
            return (Criteria) this;
        }

        public Criteria andStaffAddrGreaterThan(String value) {
            addCriterion("staff_addr >", value, "staffAddr");
            return (Criteria) this;
        }

        public Criteria andStaffAddrGreaterThanOrEqualTo(String value) {
            addCriterion("staff_addr >=", value, "staffAddr");
            return (Criteria) this;
        }

        public Criteria andStaffAddrLessThan(String value) {
            addCriterion("staff_addr <", value, "staffAddr");
            return (Criteria) this;
        }

        public Criteria andStaffAddrLessThanOrEqualTo(String value) {
            addCriterion("staff_addr <=", value, "staffAddr");
            return (Criteria) this;
        }

        public Criteria andStaffAddrLike(String value) {
            addCriterion("staff_addr like", value, "staffAddr");
            return (Criteria) this;
        }

        public Criteria andStaffAddrNotLike(String value) {
            addCriterion("staff_addr not like", value, "staffAddr");
            return (Criteria) this;
        }

        public Criteria andStaffAddrIn(List<String> values) {
            addCriterion("staff_addr in", values, "staffAddr");
            return (Criteria) this;
        }

        public Criteria andStaffAddrNotIn(List<String> values) {
            addCriterion("staff_addr not in", values, "staffAddr");
            return (Criteria) this;
        }

        public Criteria andStaffAddrBetween(String value1, String value2) {
            addCriterion("staff_addr between", value1, value2, "staffAddr");
            return (Criteria) this;
        }

        public Criteria andStaffAddrNotBetween(String value1, String value2) {
            addCriterion("staff_addr not between", value1, value2, "staffAddr");
            return (Criteria) this;
        }

        public Criteria andStaffNameIsNull() {
            addCriterion("staff_name is null");
            return (Criteria) this;
        }

        public Criteria andStaffNameIsNotNull() {
            addCriterion("staff_name is not null");
            return (Criteria) this;
        }

        public Criteria andStaffNameEqualTo(String value) {
            addCriterion("staff_name =", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotEqualTo(String value) {
            addCriterion("staff_name <>", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameGreaterThan(String value) {
            addCriterion("staff_name >", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameGreaterThanOrEqualTo(String value) {
            addCriterion("staff_name >=", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLessThan(String value) {
            addCriterion("staff_name <", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLessThanOrEqualTo(String value) {
            addCriterion("staff_name <=", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLike(String value) {
            addCriterion("staff_name like", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotLike(String value) {
            addCriterion("staff_name not like", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameIn(List<String> values) {
            addCriterion("staff_name in", values, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotIn(List<String> values) {
            addCriterion("staff_name not in", values, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameBetween(String value1, String value2) {
            addCriterion("staff_name between", value1, value2, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotBetween(String value1, String value2) {
            addCriterion("staff_name not between", value1, value2, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneIsNull() {
            addCriterion("staff_phone is null");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneIsNotNull() {
            addCriterion("staff_phone is not null");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneEqualTo(String value) {
            addCriterion("staff_phone =", value, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneNotEqualTo(String value) {
            addCriterion("staff_phone <>", value, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneGreaterThan(String value) {
            addCriterion("staff_phone >", value, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("staff_phone >=", value, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneLessThan(String value) {
            addCriterion("staff_phone <", value, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneLessThanOrEqualTo(String value) {
            addCriterion("staff_phone <=", value, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneLike(String value) {
            addCriterion("staff_phone like", value, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneNotLike(String value) {
            addCriterion("staff_phone not like", value, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneIn(List<String> values) {
            addCriterion("staff_phone in", values, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneNotIn(List<String> values) {
            addCriterion("staff_phone not in", values, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneBetween(String value1, String value2) {
            addCriterion("staff_phone between", value1, value2, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffPhoneNotBetween(String value1, String value2) {
            addCriterion("staff_phone not between", value1, value2, "staffPhone");
            return (Criteria) this;
        }

        public Criteria andStaffEmailIsNull() {
            addCriterion("staff_email is null");
            return (Criteria) this;
        }

        public Criteria andStaffEmailIsNotNull() {
            addCriterion("staff_email is not null");
            return (Criteria) this;
        }

        public Criteria andStaffEmailEqualTo(String value) {
            addCriterion("staff_email =", value, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailNotEqualTo(String value) {
            addCriterion("staff_email <>", value, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailGreaterThan(String value) {
            addCriterion("staff_email >", value, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailGreaterThanOrEqualTo(String value) {
            addCriterion("staff_email >=", value, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailLessThan(String value) {
            addCriterion("staff_email <", value, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailLessThanOrEqualTo(String value) {
            addCriterion("staff_email <=", value, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailLike(String value) {
            addCriterion("staff_email like", value, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailNotLike(String value) {
            addCriterion("staff_email not like", value, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailIn(List<String> values) {
            addCriterion("staff_email in", values, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailNotIn(List<String> values) {
            addCriterion("staff_email not in", values, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailBetween(String value1, String value2) {
            addCriterion("staff_email between", value1, value2, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andStaffEmailNotBetween(String value1, String value2) {
            addCriterion("staff_email not between", value1, value2, "staffEmail");
            return (Criteria) this;
        }

        public Criteria andJobNumberIsNull() {
            addCriterion("job_number is null");
            return (Criteria) this;
        }

        public Criteria andJobNumberIsNotNull() {
            addCriterion("job_number is not null");
            return (Criteria) this;
        }

        public Criteria andJobNumberEqualTo(String value) {
            addCriterion("job_number =", value, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberNotEqualTo(String value) {
            addCriterion("job_number <>", value, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberGreaterThan(String value) {
            addCriterion("job_number >", value, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberGreaterThanOrEqualTo(String value) {
            addCriterion("job_number >=", value, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberLessThan(String value) {
            addCriterion("job_number <", value, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberLessThanOrEqualTo(String value) {
            addCriterion("job_number <=", value, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberLike(String value) {
            addCriterion("job_number like", value, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberNotLike(String value) {
            addCriterion("job_number not like", value, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberIn(List<String> values) {
            addCriterion("job_number in", values, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberNotIn(List<String> values) {
            addCriterion("job_number not in", values, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberBetween(String value1, String value2) {
            addCriterion("job_number between", value1, value2, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberNotBetween(String value1, String value2) {
            addCriterion("job_number not between", value1, value2, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andStaffAuthorityIsNull() {
            addCriterion("staff_authority is null");
            return (Criteria) this;
        }

        public Criteria andStaffAuthorityIsNotNull() {
            addCriterion("staff_authority is not null");
            return (Criteria) this;
        }

        public Criteria andStaffAuthorityEqualTo(String value) {
            addCriterion("staff_authority =", value, "staffAuthority");
            return (Criteria) this;
        }

        public Criteria andStaffAuthorityNotEqualTo(String value) {
            addCriterion("staff_authority <>", value, "staffAuthority");
            return (Criteria) this;
        }

        public Criteria andStaffAuthorityGreaterThan(String value) {
            addCriterion("staff_authority >", value, "staffAuthority");
            return (Criteria) this;
        }

        public Criteria andStaffAuthorityGreaterThanOrEqualTo(String value) {
            addCriterion("staff_authority >=", value, "staffAuthority");
            return (Criteria) this;
        }

        public Criteria andStaffAuthorityLessThan(String value) {
            addCriterion("staff_authority <", value, "staffAuthority");
            return (Criteria) this;
        }

        public Criteria andStaffAuthorityLessThanOrEqualTo(String value) {
            addCriterion("staff_authority <=", value, "staffAuthority");
            return (Criteria) this;
        }

        public Criteria andStaffAuthorityLike(String value) {
            addCriterion("staff_authority like", value, "staffAuthority");
            return (Criteria) this;
        }

        public Criteria andStaffAuthorityNotLike(String value) {
            addCriterion("staff_authority not like", value, "staffAuthority");
            return (Criteria) this;
        }

        public Criteria andStaffAuthorityIn(List<String> values) {
            addCriterion("staff_authority in", values, "staffAuthority");
            return (Criteria) this;
        }

        public Criteria andStaffAuthorityNotIn(List<String> values) {
            addCriterion("staff_authority not in", values, "staffAuthority");
            return (Criteria) this;
        }

        public Criteria andStaffAuthorityBetween(String value1, String value2) {
            addCriterion("staff_authority between", value1, value2, "staffAuthority");
            return (Criteria) this;
        }

        public Criteria andStaffAuthorityNotBetween(String value1, String value2) {
            addCriterion("staff_authority not between", value1, value2, "staffAuthority");
            return (Criteria) this;
        }

        public Criteria andStaffDescIsNull() {
            addCriterion("staff_desc is null");
            return (Criteria) this;
        }

        public Criteria andStaffDescIsNotNull() {
            addCriterion("staff_desc is not null");
            return (Criteria) this;
        }

        public Criteria andStaffDescEqualTo(String value) {
            addCriterion("staff_desc =", value, "staffDesc");
            return (Criteria) this;
        }

        public Criteria andStaffDescNotEqualTo(String value) {
            addCriterion("staff_desc <>", value, "staffDesc");
            return (Criteria) this;
        }

        public Criteria andStaffDescGreaterThan(String value) {
            addCriterion("staff_desc >", value, "staffDesc");
            return (Criteria) this;
        }

        public Criteria andStaffDescGreaterThanOrEqualTo(String value) {
            addCriterion("staff_desc >=", value, "staffDesc");
            return (Criteria) this;
        }

        public Criteria andStaffDescLessThan(String value) {
            addCriterion("staff_desc <", value, "staffDesc");
            return (Criteria) this;
        }

        public Criteria andStaffDescLessThanOrEqualTo(String value) {
            addCriterion("staff_desc <=", value, "staffDesc");
            return (Criteria) this;
        }

        public Criteria andStaffDescLike(String value) {
            addCriterion("staff_desc like", value, "staffDesc");
            return (Criteria) this;
        }

        public Criteria andStaffDescNotLike(String value) {
            addCriterion("staff_desc not like", value, "staffDesc");
            return (Criteria) this;
        }

        public Criteria andStaffDescIn(List<String> values) {
            addCriterion("staff_desc in", values, "staffDesc");
            return (Criteria) this;
        }

        public Criteria andStaffDescNotIn(List<String> values) {
            addCriterion("staff_desc not in", values, "staffDesc");
            return (Criteria) this;
        }

        public Criteria andStaffDescBetween(String value1, String value2) {
            addCriterion("staff_desc between", value1, value2, "staffDesc");
            return (Criteria) this;
        }

        public Criteria andStaffDescNotBetween(String value1, String value2) {
            addCriterion("staff_desc not between", value1, value2, "staffDesc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table staff
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 22 20:20:17 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table staff
     *
     * @mbggenerated Sun Apr 22 20:20:17 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}