package cn.jbg.cmab.backend.checkout.bean;

import java.util.Date;

public class Checkout {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkout.checkout_id
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    private Long checkoutId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkout.checkout_type
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    private Integer checkoutType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkout.audit_id
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    private Long auditId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkout.checkout_time
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    private Date checkoutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkout.checkout_desc
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    private String checkoutDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkout.people_type
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    private Integer peopleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkout.people_id
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    private Long peopleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkout.checkout_id
     *
     * @return the value of checkout.checkout_id
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    public Long getCheckoutId() {
        return checkoutId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkout.checkout_id
     *
     * @param checkoutId the value for checkout.checkout_id
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    public void setCheckoutId(Long checkoutId) {
        this.checkoutId = checkoutId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkout.checkout_type
     *
     * @return the value of checkout.checkout_type
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    public Integer getCheckoutType() {
        return checkoutType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkout.checkout_type
     *
     * @param checkoutType the value for checkout.checkout_type
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    public void setCheckoutType(Integer checkoutType) {
        this.checkoutType = checkoutType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkout.audit_id
     *
     * @return the value of checkout.audit_id
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    public Long getAuditId() {
        return auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkout.audit_id
     *
     * @param auditId the value for checkout.audit_id
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    public void setAuditId(Long auditId) {
        this.auditId = auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkout.checkout_time
     *
     * @return the value of checkout.checkout_time
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    public Date getCheckoutTime() {
        return checkoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkout.checkout_time
     *
     * @param checkoutTime the value for checkout.checkout_time
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    public void setCheckoutTime(Date checkoutTime) {
        this.checkoutTime = checkoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkout.checkout_desc
     *
     * @return the value of checkout.checkout_desc
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    public String getCheckoutDesc() {
        return checkoutDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkout.checkout_desc
     *
     * @param checkoutDesc the value for checkout.checkout_desc
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    public void setCheckoutDesc(String checkoutDesc) {
        this.checkoutDesc = checkoutDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkout.people_type
     *
     * @return the value of checkout.people_type
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    public Integer getPeopleType() {
        return peopleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkout.people_type
     *
     * @param peopleType the value for checkout.people_type
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    public void setPeopleType(Integer peopleType) {
        this.peopleType = peopleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkout.people_id
     *
     * @return the value of checkout.people_id
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    public Long getPeopleId() {
        return peopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkout.people_id
     *
     * @param peopleId the value for checkout.people_id
     *
     * @mbggenerated Sat Apr 28 16:08:58 CST 2018
     */
    public void setPeopleId(Long peopleId) {
        this.peopleId = peopleId;
    }
}