package cn.jbg.cmab.backend.checkout.bean;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_id
     *
     * @mbggenerated Sat Apr 28 13:50:44 CST 2018
     */
    private Long messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_content
     *
     * @mbggenerated Sat Apr 28 13:50:44 CST 2018
     */
    private String messageContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_type
     *
     * @mbggenerated Sat Apr 28 13:50:44 CST 2018
     */
    private Integer messageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_time
     *
     * @mbggenerated Sat Apr 28 13:50:44 CST 2018
     */
    private Date messageTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.people_type
     *
     * @mbggenerated Sat Apr 28 13:50:44 CST 2018
     */
    private Integer peopleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.people_id
     *
     * @mbggenerated Sat Apr 28 13:50:44 CST 2018
     */
    private Long peopleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_id
     *
     * @return the value of message.message_id
     *
     * @mbggenerated Sat Apr 28 13:50:44 CST 2018
     */
    public Long getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_id
     *
     * @param messageId the value for message.message_id
     *
     * @mbggenerated Sat Apr 28 13:50:44 CST 2018
     */
    public void setMessageId(Long messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_content
     *
     * @return the value of message.message_content
     *
     * @mbggenerated Sat Apr 28 13:50:44 CST 2018
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_content
     *
     * @param messageContent the value for message.message_content
     *
     * @mbggenerated Sat Apr 28 13:50:44 CST 2018
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_type
     *
     * @return the value of message.message_type
     *
     * @mbggenerated Sat Apr 28 13:50:44 CST 2018
     */
    public Integer getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_type
     *
     * @param messageType the value for message.message_type
     *
     * @mbggenerated Sat Apr 28 13:50:44 CST 2018
     */
    public void setMessageType(Integer messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_time
     *
     * @return the value of message.message_time
     *
     * @mbggenerated Sat Apr 28 13:50:44 CST 2018
     */
    public Date getMessageTime() {
        return messageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_time
     *
     * @param messageTime the value for message.message_time
     *
     * @mbggenerated Sat Apr 28 13:50:44 CST 2018
     */
    public void setMessageTime(Date messageTime) {
        this.messageTime = messageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.people_type
     *
     * @return the value of message.people_type
     *
     * @mbggenerated Sat Apr 28 13:50:44 CST 2018
     */
    public Integer getPeopleType() {
        return peopleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.people_type
     *
     * @param peopleType the value for message.people_type
     *
     * @mbggenerated Sat Apr 28 13:50:44 CST 2018
     */
    public void setPeopleType(Integer peopleType) {
        this.peopleType = peopleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.people_id
     *
     * @return the value of message.people_id
     *
     * @mbggenerated Sat Apr 28 13:50:44 CST 2018
     */
    public Long getPeopleId() {
        return peopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.people_id
     *
     * @param peopleId the value for message.people_id
     *
     * @mbggenerated Sat Apr 28 13:50:44 CST 2018
     */
    public void setPeopleId(Long peopleId) {
        this.peopleId = peopleId;
    }
}