package cn.jbg.cmab.backend.system.bean;

public class SystemRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rule.rule_id
     *
     * @mbggenerated Wed May 02 22:31:46 CST 2018
     */
    private Long ruleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rule.rule_type
     *
     * @mbggenerated Wed May 02 22:31:46 CST 2018
     */
    private String ruleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rule.rule_code
     *
     * @mbggenerated Wed May 02 22:31:46 CST 2018
     */
    private String ruleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rule.rule_key
     *
     * @mbggenerated Wed May 02 22:31:46 CST 2018
     */
    private Integer ruleKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rule.rule_value
     *
     * @mbggenerated Wed May 02 22:31:46 CST 2018
     */
    private String ruleValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rule.rule_desc
     *
     * @mbggenerated Wed May 02 22:31:46 CST 2018
     */
    private String ruleDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rule.rule_id
     *
     * @return the value of system_rule.rule_id
     *
     * @mbggenerated Wed May 02 22:31:46 CST 2018
     */
    public Long getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rule.rule_id
     *
     * @param ruleId the value for system_rule.rule_id
     *
     * @mbggenerated Wed May 02 22:31:46 CST 2018
     */
    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rule.rule_type
     *
     * @return the value of system_rule.rule_type
     *
     * @mbggenerated Wed May 02 22:31:46 CST 2018
     */
    public String getRuleType() {
        return ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rule.rule_type
     *
     * @param ruleType the value for system_rule.rule_type
     *
     * @mbggenerated Wed May 02 22:31:46 CST 2018
     */
    public void setRuleType(String ruleType) {
        this.ruleType = ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rule.rule_code
     *
     * @return the value of system_rule.rule_code
     *
     * @mbggenerated Wed May 02 22:31:46 CST 2018
     */
    public String getRuleCode() {
        return ruleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rule.rule_code
     *
     * @param ruleCode the value for system_rule.rule_code
     *
     * @mbggenerated Wed May 02 22:31:46 CST 2018
     */
    public void setRuleCode(String ruleCode) {
        this.ruleCode = ruleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rule.rule_key
     *
     * @return the value of system_rule.rule_key
     *
     * @mbggenerated Wed May 02 22:31:46 CST 2018
     */
    public Integer getRuleKey() {
        return ruleKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rule.rule_key
     *
     * @param ruleKey the value for system_rule.rule_key
     *
     * @mbggenerated Wed May 02 22:31:46 CST 2018
     */
    public void setRuleKey(Integer ruleKey) {
        this.ruleKey = ruleKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rule.rule_value
     *
     * @return the value of system_rule.rule_value
     *
     * @mbggenerated Wed May 02 22:31:46 CST 2018
     */
    public String getRuleValue() {
        return ruleValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rule.rule_value
     *
     * @param ruleValue the value for system_rule.rule_value
     *
     * @mbggenerated Wed May 02 22:31:46 CST 2018
     */
    public void setRuleValue(String ruleValue) {
        this.ruleValue = ruleValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rule.rule_desc
     *
     * @return the value of system_rule.rule_desc
     *
     * @mbggenerated Wed May 02 22:31:46 CST 2018
     */
    public String getRuleDesc() {
        return ruleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rule.rule_desc
     *
     * @param ruleDesc the value for system_rule.rule_desc
     *
     * @mbggenerated Wed May 02 22:31:46 CST 2018
     */
    public void setRuleDesc(String ruleDesc) {
        this.ruleDesc = ruleDesc;
    }
}