package cn.jbg.cmab.backend.mall.dao;

import cn.jbg.cmab.backend.mall.bean.UsedGoods;
import cn.jbg.cmab.backend.mall.bean.UsedGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsedGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table used_goods
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    int countByExample(UsedGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table used_goods
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    int deleteByExample(UsedGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table used_goods
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    int deleteByPrimaryKey(Long goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table used_goods
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    int insert(UsedGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table used_goods
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    int insertSelective(UsedGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table used_goods
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    List<UsedGoods> selectByExample(UsedGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table used_goods
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    UsedGoods selectByPrimaryKey(Long goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table used_goods
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") UsedGoods record, @Param("example") UsedGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table used_goods
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    int updateByExample(@Param("record") UsedGoods record, @Param("example") UsedGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table used_goods
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    int updateByPrimaryKeySelective(UsedGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table used_goods
     *
     * @mbggenerated Fri May 11 15:06:02 CST 2018
     */
    int updateByPrimaryKey(UsedGoods record);
}