package cn.jbg.cmab.backend.users.bean;

import java.math.BigDecimal;
import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_id
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_id
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.item_id
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.item_num
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    private Integer itemNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.item_price
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    private BigDecimal itemPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.member_benefit
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    private String memberBenefit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_price
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    private BigDecimal orderPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_note
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    private String orderNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_time
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_tag
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    private Integer orderTag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_id
     *
     * @return the value of orders.order_id
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_id
     *
     * @param orderId the value for orders.order_id
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_id
     *
     * @return the value of orders.user_id
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_id
     *
     * @param userId the value for orders.user_id
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.item_id
     *
     * @return the value of orders.item_id
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.item_id
     *
     * @param itemId the value for orders.item_id
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.item_num
     *
     * @return the value of orders.item_num
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public Integer getItemNum() {
        return itemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.item_num
     *
     * @param itemNum the value for orders.item_num
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public void setItemNum(Integer itemNum) {
        this.itemNum = itemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.item_price
     *
     * @return the value of orders.item_price
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public BigDecimal getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.item_price
     *
     * @param itemPrice the value for orders.item_price
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public void setItemPrice(BigDecimal itemPrice) {
        this.itemPrice = itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.member_benefit
     *
     * @return the value of orders.member_benefit
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public String getMemberBenefit() {
        return memberBenefit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.member_benefit
     *
     * @param memberBenefit the value for orders.member_benefit
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public void setMemberBenefit(String memberBenefit) {
        this.memberBenefit = memberBenefit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_price
     *
     * @return the value of orders.order_price
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public BigDecimal getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_price
     *
     * @param orderPrice the value for orders.order_price
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public void setOrderPrice(BigDecimal orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_note
     *
     * @return the value of orders.order_note
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public String getOrderNote() {
        return orderNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_note
     *
     * @param orderNote the value for orders.order_note
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public void setOrderNote(String orderNote) {
        this.orderNote = orderNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_time
     *
     * @return the value of orders.order_time
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_time
     *
     * @param orderTime the value for orders.order_time
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_tag
     *
     * @return the value of orders.order_tag
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public Integer getOrderTag() {
        return orderTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_tag
     *
     * @param orderTag the value for orders.order_tag
     *
     * @mbggenerated Sun Apr 22 20:25:40 CST 2018
     */
    public void setOrderTag(Integer orderTag) {
        this.orderTag = orderTag;
    }
}