package cn.jbg.cmab.backend.users.bean;

import java.util.ArrayList;
import java.util.List;

public class ShoppingCarExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shopping_car
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shopping_car
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shopping_car
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public ShoppingCarExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shopping_car
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andShcIdIsNull() {
            addCriterion("shc_id is null");
            return (Criteria) this;
        }

        public Criteria andShcIdIsNotNull() {
            addCriterion("shc_id is not null");
            return (Criteria) this;
        }

        public Criteria andShcIdEqualTo(Long value) {
            addCriterion("shc_id =", value, "shcId");
            return (Criteria) this;
        }

        public Criteria andShcIdNotEqualTo(Long value) {
            addCriterion("shc_id <>", value, "shcId");
            return (Criteria) this;
        }

        public Criteria andShcIdGreaterThan(Long value) {
            addCriterion("shc_id >", value, "shcId");
            return (Criteria) this;
        }

        public Criteria andShcIdGreaterThanOrEqualTo(Long value) {
            addCriterion("shc_id >=", value, "shcId");
            return (Criteria) this;
        }

        public Criteria andShcIdLessThan(Long value) {
            addCriterion("shc_id <", value, "shcId");
            return (Criteria) this;
        }

        public Criteria andShcIdLessThanOrEqualTo(Long value) {
            addCriterion("shc_id <=", value, "shcId");
            return (Criteria) this;
        }

        public Criteria andShcIdIn(List<Long> values) {
            addCriterion("shc_id in", values, "shcId");
            return (Criteria) this;
        }

        public Criteria andShcIdNotIn(List<Long> values) {
            addCriterion("shc_id not in", values, "shcId");
            return (Criteria) this;
        }

        public Criteria andShcIdBetween(Long value1, Long value2) {
            addCriterion("shc_id between", value1, value2, "shcId");
            return (Criteria) this;
        }

        public Criteria andShcIdNotBetween(Long value1, Long value2) {
            addCriterion("shc_id not between", value1, value2, "shcId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNull() {
            addCriterion("item_id is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("item_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(Long value) {
            addCriterion("item_id =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(Long value) {
            addCriterion("item_id <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(Long value) {
            addCriterion("item_id >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(Long value) {
            addCriterion("item_id >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(Long value) {
            addCriterion("item_id <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(Long value) {
            addCriterion("item_id <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<Long> values) {
            addCriterion("item_id in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<Long> values) {
            addCriterion("item_id not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(Long value1, Long value2) {
            addCriterion("item_id between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(Long value1, Long value2) {
            addCriterion("item_id not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemNumIsNull() {
            addCriterion("item_num is null");
            return (Criteria) this;
        }

        public Criteria andItemNumIsNotNull() {
            addCriterion("item_num is not null");
            return (Criteria) this;
        }

        public Criteria andItemNumEqualTo(Integer value) {
            addCriterion("item_num =", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumNotEqualTo(Integer value) {
            addCriterion("item_num <>", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumGreaterThan(Integer value) {
            addCriterion("item_num >", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_num >=", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumLessThan(Integer value) {
            addCriterion("item_num <", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumLessThanOrEqualTo(Integer value) {
            addCriterion("item_num <=", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumIn(List<Integer> values) {
            addCriterion("item_num in", values, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumNotIn(List<Integer> values) {
            addCriterion("item_num not in", values, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumBetween(Integer value1, Integer value2) {
            addCriterion("item_num between", value1, value2, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumNotBetween(Integer value1, Integer value2) {
            addCriterion("item_num not between", value1, value2, "itemNum");
            return (Criteria) this;
        }

        public Criteria andShcDescIsNull() {
            addCriterion("shc_desc is null");
            return (Criteria) this;
        }

        public Criteria andShcDescIsNotNull() {
            addCriterion("shc_desc is not null");
            return (Criteria) this;
        }

        public Criteria andShcDescEqualTo(String value) {
            addCriterion("shc_desc =", value, "shcDesc");
            return (Criteria) this;
        }

        public Criteria andShcDescNotEqualTo(String value) {
            addCriterion("shc_desc <>", value, "shcDesc");
            return (Criteria) this;
        }

        public Criteria andShcDescGreaterThan(String value) {
            addCriterion("shc_desc >", value, "shcDesc");
            return (Criteria) this;
        }

        public Criteria andShcDescGreaterThanOrEqualTo(String value) {
            addCriterion("shc_desc >=", value, "shcDesc");
            return (Criteria) this;
        }

        public Criteria andShcDescLessThan(String value) {
            addCriterion("shc_desc <", value, "shcDesc");
            return (Criteria) this;
        }

        public Criteria andShcDescLessThanOrEqualTo(String value) {
            addCriterion("shc_desc <=", value, "shcDesc");
            return (Criteria) this;
        }

        public Criteria andShcDescLike(String value) {
            addCriterion("shc_desc like", value, "shcDesc");
            return (Criteria) this;
        }

        public Criteria andShcDescNotLike(String value) {
            addCriterion("shc_desc not like", value, "shcDesc");
            return (Criteria) this;
        }

        public Criteria andShcDescIn(List<String> values) {
            addCriterion("shc_desc in", values, "shcDesc");
            return (Criteria) this;
        }

        public Criteria andShcDescNotIn(List<String> values) {
            addCriterion("shc_desc not in", values, "shcDesc");
            return (Criteria) this;
        }

        public Criteria andShcDescBetween(String value1, String value2) {
            addCriterion("shc_desc between", value1, value2, "shcDesc");
            return (Criteria) this;
        }

        public Criteria andShcDescNotBetween(String value1, String value2) {
            addCriterion("shc_desc not between", value1, value2, "shcDesc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shopping_car
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 22 20:27:49 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shopping_car
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}