package cn.jbg.cmab.backend.users.bean;

public class ShoppingCar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.shc_id
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    private Long shcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.user_id
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.item_id
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.item_num
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    private Integer itemNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.shc_desc
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    private String shcDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.shc_id
     *
     * @return the value of shopping_car.shc_id
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public Long getShcId() {
        return shcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.shc_id
     *
     * @param shcId the value for shopping_car.shc_id
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public void setShcId(Long shcId) {
        this.shcId = shcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.user_id
     *
     * @return the value of shopping_car.user_id
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.user_id
     *
     * @param userId the value for shopping_car.user_id
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.item_id
     *
     * @return the value of shopping_car.item_id
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.item_id
     *
     * @param itemId the value for shopping_car.item_id
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.item_num
     *
     * @return the value of shopping_car.item_num
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public Integer getItemNum() {
        return itemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.item_num
     *
     * @param itemNum the value for shopping_car.item_num
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public void setItemNum(Integer itemNum) {
        this.itemNum = itemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.shc_desc
     *
     * @return the value of shopping_car.shc_desc
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public String getShcDesc() {
        return shcDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.shc_desc
     *
     * @param shcDesc the value for shopping_car.shc_desc
     *
     * @mbggenerated Sun Apr 22 20:27:49 CST 2018
     */
    public void setShcDesc(String shcDesc) {
        this.shcDesc = shcDesc;
    }
}