package cn.jbg.cmab.backend.users.bean;

public class UsersSetting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_setting.setting_id
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    private Long settingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_setting.user_id
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_setting.user_realname
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    private String userRealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_setting.users_post
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    private String usersPost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_setting.phone_number
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_setting.email
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_setting.login_password
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_setting.pay_password
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    private String payPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_setting.setting_id
     *
     * @return the value of users_setting.setting_id
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    public Long getSettingId() {
        return settingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_setting.setting_id
     *
     * @param settingId the value for users_setting.setting_id
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    public void setSettingId(Long settingId) {
        this.settingId = settingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_setting.user_id
     *
     * @return the value of users_setting.user_id
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_setting.user_id
     *
     * @param userId the value for users_setting.user_id
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_setting.user_realname
     *
     * @return the value of users_setting.user_realname
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    public String getUserRealname() {
        return userRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_setting.user_realname
     *
     * @param userRealname the value for users_setting.user_realname
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    public void setUserRealname(String userRealname) {
        this.userRealname = userRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_setting.users_post
     *
     * @return the value of users_setting.users_post
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    public String getUsersPost() {
        return usersPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_setting.users_post
     *
     * @param usersPost the value for users_setting.users_post
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    public void setUsersPost(String usersPost) {
        this.usersPost = usersPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_setting.phone_number
     *
     * @return the value of users_setting.phone_number
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_setting.phone_number
     *
     * @param phoneNumber the value for users_setting.phone_number
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_setting.email
     *
     * @return the value of users_setting.email
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_setting.email
     *
     * @param email the value for users_setting.email
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_setting.login_password
     *
     * @return the value of users_setting.login_password
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_setting.login_password
     *
     * @param loginPassword the value for users_setting.login_password
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_setting.pay_password
     *
     * @return the value of users_setting.pay_password
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    public String getPayPassword() {
        return payPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_setting.pay_password
     *
     * @param payPassword the value for users_setting.pay_password
     *
     * @mbggenerated Sun Apr 22 20:37:13 CST 2018
     */
    public void setPayPassword(String payPassword) {
        this.payPassword = payPassword;
    }
}