package cn.jbg.cmab.backend.users.bean;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.openid
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.nick_name
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.avatar_url
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    private String avatarUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.gender
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.city
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.province
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.country
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.language
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_desc
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    private String userDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.openid
     *
     * @return the value of users.openid
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.openid
     *
     * @param openid the value for users.openid
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.nick_name
     *
     * @return the value of users.nick_name
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.nick_name
     *
     * @param nickName the value for users.nick_name
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.avatar_url
     *
     * @return the value of users.avatar_url
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.avatar_url
     *
     * @param avatarUrl the value for users.avatar_url
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.gender
     *
     * @return the value of users.gender
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.gender
     *
     * @param gender the value for users.gender
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.city
     *
     * @return the value of users.city
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.city
     *
     * @param city the value for users.city
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.province
     *
     * @return the value of users.province
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.province
     *
     * @param province the value for users.province
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.country
     *
     * @return the value of users.country
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.country
     *
     * @param country the value for users.country
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.language
     *
     * @return the value of users.language
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.language
     *
     * @param language the value for users.language
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_desc
     *
     * @return the value of users.user_desc
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public String getUserDesc() {
        return userDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_desc
     *
     * @param userDesc the value for users.user_desc
     *
     * @mbggenerated Fri Apr 27 00:21:30 CST 2018
     */
    public void setUserDesc(String userDesc) {
        this.userDesc = userDesc;
    }
}