package cn.jbg.cmab.backend.admin.dao;

import cn.jbg.cmab.backend.admin.bean.Authority;
import cn.jbg.cmab.backend.admin.bean.AuthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Sun Apr 22 20:12:41 CST 2018
     */
    int countByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Sun Apr 22 20:12:41 CST 2018
     */
    int deleteByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Sun Apr 22 20:12:41 CST 2018
     */
    int deleteByPrimaryKey(Long authorityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Sun Apr 22 20:12:41 CST 2018
     */
    int insert(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Sun Apr 22 20:12:41 CST 2018
     */
    int insertSelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Sun Apr 22 20:12:41 CST 2018
     */
    List<Authority> selectByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Sun Apr 22 20:12:41 CST 2018
     */
    Authority selectByPrimaryKey(Long authorityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Sun Apr 22 20:12:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") Authority record, @Param("example") AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Sun Apr 22 20:12:41 CST 2018
     */
    int updateByExample(@Param("record") Authority record, @Param("example") AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Sun Apr 22 20:12:41 CST 2018
     */
    int updateByPrimaryKeySelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Sun Apr 22 20:12:41 CST 2018
     */
    int updateByPrimaryKey(Authority record);
}