package cn.jbg.cmab.backend.business.bean;

public class Business {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.business_id
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    private Long businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.business_addr
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    private String businessAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.business_name
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    private String businessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.business_manager
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    private String businessManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.business_phone
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    private String businessPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.business_email
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    private String businessEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.business_desc
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    private String businessDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.business_id
     *
     * @return the value of business.business_id
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.business_id
     *
     * @param businessId the value for business.business_id
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.business_addr
     *
     * @return the value of business.business_addr
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    public String getBusinessAddr() {
        return businessAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.business_addr
     *
     * @param businessAddr the value for business.business_addr
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    public void setBusinessAddr(String businessAddr) {
        this.businessAddr = businessAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.business_name
     *
     * @return the value of business.business_name
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.business_name
     *
     * @param businessName the value for business.business_name
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.business_manager
     *
     * @return the value of business.business_manager
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    public String getBusinessManager() {
        return businessManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.business_manager
     *
     * @param businessManager the value for business.business_manager
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    public void setBusinessManager(String businessManager) {
        this.businessManager = businessManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.business_phone
     *
     * @return the value of business.business_phone
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    public String getBusinessPhone() {
        return businessPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.business_phone
     *
     * @param businessPhone the value for business.business_phone
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    public void setBusinessPhone(String businessPhone) {
        this.businessPhone = businessPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.business_email
     *
     * @return the value of business.business_email
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    public String getBusinessEmail() {
        return businessEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.business_email
     *
     * @param businessEmail the value for business.business_email
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    public void setBusinessEmail(String businessEmail) {
        this.businessEmail = businessEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.business_desc
     *
     * @return the value of business.business_desc
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    public String getBusinessDesc() {
        return businessDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.business_desc
     *
     * @param businessDesc the value for business.business_desc
     *
     * @mbggenerated Thu Apr 26 21:26:49 CST 2018
     */
    public void setBusinessDesc(String businessDesc) {
        this.businessDesc = businessDesc;
    }
}