package cn.jbg.cmab.backend.module.bean;

public class Module {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.module_id
     *
     * @mbggenerated Sun Apr 22 20:24:33 CST 2018
     */
    private Long moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.module_name
     *
     * @mbggenerated Sun Apr 22 20:24:33 CST 2018
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.module_url
     *
     * @mbggenerated Sun Apr 22 20:24:33 CST 2018
     */
    private String moduleUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.module_icon
     *
     * @mbggenerated Sun Apr 22 20:24:33 CST 2018
     */
    private String moduleIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.module_desc
     *
     * @mbggenerated Sun Apr 22 20:24:33 CST 2018
     */
    private String moduleDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.module_id
     *
     * @return the value of module.module_id
     *
     * @mbggenerated Sun Apr 22 20:24:33 CST 2018
     */
    public Long getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.module_id
     *
     * @param moduleId the value for module.module_id
     *
     * @mbggenerated Sun Apr 22 20:24:33 CST 2018
     */
    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.module_name
     *
     * @return the value of module.module_name
     *
     * @mbggenerated Sun Apr 22 20:24:33 CST 2018
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.module_name
     *
     * @param moduleName the value for module.module_name
     *
     * @mbggenerated Sun Apr 22 20:24:33 CST 2018
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.module_url
     *
     * @return the value of module.module_url
     *
     * @mbggenerated Sun Apr 22 20:24:33 CST 2018
     */
    public String getModuleUrl() {
        return moduleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.module_url
     *
     * @param moduleUrl the value for module.module_url
     *
     * @mbggenerated Sun Apr 22 20:24:33 CST 2018
     */
    public void setModuleUrl(String moduleUrl) {
        this.moduleUrl = moduleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.module_icon
     *
     * @return the value of module.module_icon
     *
     * @mbggenerated Sun Apr 22 20:24:33 CST 2018
     */
    public String getModuleIcon() {
        return moduleIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.module_icon
     *
     * @param moduleIcon the value for module.module_icon
     *
     * @mbggenerated Sun Apr 22 20:24:33 CST 2018
     */
    public void setModuleIcon(String moduleIcon) {
        this.moduleIcon = moduleIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.module_desc
     *
     * @return the value of module.module_desc
     *
     * @mbggenerated Sun Apr 22 20:24:33 CST 2018
     */
    public String getModuleDesc() {
        return moduleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.module_desc
     *
     * @param moduleDesc the value for module.module_desc
     *
     * @mbggenerated Sun Apr 22 20:24:33 CST 2018
     */
    public void setModuleDesc(String moduleDesc) {
        this.moduleDesc = moduleDesc;
    }
}