package cn.jbg.cmab.backend.checkout.dao;

import cn.jbg.cmab.backend.checkout.bean.Checkout;
import cn.jbg.cmab.backend.checkout.bean.CheckoutExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckoutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkout
     *
     * @mbggenerated Sat Apr 28 16:08:59 CST 2018
     */
    int countByExample(CheckoutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkout
     *
     * @mbggenerated Sat Apr 28 16:08:59 CST 2018
     */
    int deleteByExample(CheckoutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkout
     *
     * @mbggenerated Sat Apr 28 16:08:59 CST 2018
     */
    int deleteByPrimaryKey(Long checkoutId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkout
     *
     * @mbggenerated Sat Apr 28 16:08:59 CST 2018
     */
    int insert(Checkout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkout
     *
     * @mbggenerated Sat Apr 28 16:08:59 CST 2018
     */
    int insertSelective(Checkout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkout
     *
     * @mbggenerated Sat Apr 28 16:08:59 CST 2018
     */
    List<Checkout> selectByExample(CheckoutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkout
     *
     * @mbggenerated Sat Apr 28 16:08:59 CST 2018
     */
    Checkout selectByPrimaryKey(Long checkoutId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkout
     *
     * @mbggenerated Sat Apr 28 16:08:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") Checkout record, @Param("example") CheckoutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkout
     *
     * @mbggenerated Sat Apr 28 16:08:59 CST 2018
     */
    int updateByExample(@Param("record") Checkout record, @Param("example") CheckoutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkout
     *
     * @mbggenerated Sat Apr 28 16:08:59 CST 2018
     */
    int updateByPrimaryKeySelective(Checkout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkout
     *
     * @mbggenerated Sat Apr 28 16:08:59 CST 2018
     */
    int updateByPrimaryKey(Checkout record);
}